/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package system;

import config.config;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author PC1
 */
public class prodcutsadmin extends javax.swing.JFrame {

    public int adminId;
    Color defaultColor = new Color(236, 240, 241);
    Color activeColor = new Color(255, 204, 204);

    /**
     * Creates new form prodcutsadmin
     */
    public prodcutsadmin() {
        this(0);
    }

    public prodcutsadmin(int adminId) {
        initComponents();
        this.adminId = adminId;
        ensureProductsTable();
        displayProducts();
        JButton[] buttons = { dashboard, products, reports, user, logout };
        for (JButton btn : buttons) {
            btn.setOpaque(true);
            btn.setContentAreaFilled(true);
            btn.setBorderPainted(false);
            btn.setBackground(defaultColor);
        }
        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    fillFormFromSelectedRow();
                }
            }
        });
    }

    private void resetMenuColors() {
        JButton[] buttons = { dashboard, products, reports, user, logout };
        for (JButton btn : buttons) {
            btn.setBackground(defaultColor);
        }
    }

    private void ensureProductsTable() {
        config.seedDefaultProducts();
    }

    private void displayProducts() {
        String sql = "SELECT p_id AS 'ID', product_name AS 'Product Name', price AS 'Price', " +
                "quantity AS 'Quantity', expiration_date AS 'Expiration', status AS 'Status' " +
                "FROM tbl_products ORDER BY p_id DESC";
        config con = new config();
        con.displayData(sql, jTable1);
    }

    private void fillFormFromSelectedRow() {
        int row = jTable1.getSelectedRow();
        if (row < 0) return;
        txtID1.setText(String.valueOf(jTable1.getValueAt(row, 0)));
        txtproduct.setText(jTable1.getValueAt(row, 1) != null ? jTable1.getValueAt(row, 1).toString() : "");
        txtprice.setText(jTable1.getValueAt(row, 2) != null ? jTable1.getValueAt(row, 2).toString() : "");
        txtquantity.setText(jTable1.getValueAt(row, 3) != null ? jTable1.getValueAt(row, 3).toString() : "");
        txtexpire.setText(jTable1.getValueAt(row, 4) != null ? jTable1.getValueAt(row, 4).toString() : "");
        txtstatus.setText(jTable1.getValueAt(row, 5) != null ? jTable1.getValueAt(row, 5).toString() : "");
    }

    private void clearForm() {
        txtID1.setText("");
        txtproduct.setText("");
        txtprice.setText("");
        txtquantity.setText("");
        txtexpire.setText("");
        txtstatus.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dashboard = new javax.swing.JButton();
        products = new javax.swing.JButton();
        reports = new javax.swing.JButton();
        user = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        adminprofile = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtID1 = new javax.swing.JTextField();
        Id = new javax.swing.JLabel();
        Product = new javax.swing.JLabel();
        txtproduct = new javax.swing.JTextField();
        Price = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        Quantity = new javax.swing.JLabel();
        txtquantity = new javax.swing.JTextField();
        Expiration = new javax.swing.JLabel();
        txtexpire = new javax.swing.JTextField();
        Price1 = new javax.swing.JLabel();
        txtstatus = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        add = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PRODUCTS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 250, 50));

        dashboard.setBackground(new java.awt.Color(255, 255, 255));
        dashboard.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dashboard.setText("Dashboard");
        dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMouseClicked(evt);
            }
        });
        dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardActionPerformed(evt);
            }
        });
        jPanel2.add(dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 150, 30));

        products.setBackground(new java.awt.Color(255, 255, 255));
        products.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        products.setText("Products");
        products.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productsMouseClicked(evt);
            }
        });
        products.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productsActionPerformed(evt);
            }
        });
        jPanel2.add(products, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 150, 30));

        reports.setBackground(new java.awt.Color(255, 255, 255));
        reports.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        reports.setText("Reports");
        reports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportsMouseClicked(evt);
            }
        });
        reports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportsActionPerformed(evt);
            }
        });
        jPanel2.add(reports, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 150, 30));

        user.setBackground(new java.awt.Color(255, 255, 255));
        user.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        user.setText("User");
        user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userMouseClicked(evt);
            }
        });
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        jPanel2.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 150, 30));

        logout.setBackground(new java.awt.Color(255, 51, 51));
        logout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 0, 0));
        logout.setText("LOG OUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel2.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 150, 30));

        adminprofile.setBackground(new java.awt.Color(255, 255, 255));
        adminprofile.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        adminprofile.setText("Profile");
        adminprofile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminprofileMouseClicked(evt);
            }
        });
        adminprofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminprofileActionPerformed(evt);
            }
        });
        jPanel2.add(adminprofile, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 150, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 500));

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtID1ActionPerformed(evt);
            }
        });
        jPanel3.add(txtID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 120, 30));

        Id.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Id.setText("ID:");
        jPanel3.add(Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        Product.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Product.setText("Product Name:");
        jPanel3.add(Product, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        txtproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtproductActionPerformed(evt);
            }
        });
        jPanel3.add(txtproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 120, 30));

        Price.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Price.setText("Price:");
        jPanel3.add(Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        txtprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpriceActionPerformed(evt);
            }
        });
        jPanel3.add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 120, 30));

        Quantity.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Quantity.setText("Quantity:");
        jPanel3.add(Quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        txtquantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtquantityActionPerformed(evt);
            }
        });
        jPanel3.add(txtquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 120, 30));

        Expiration.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Expiration.setText("Expiration Date:");
        jPanel3.add(Expiration, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        txtexpire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtexpireActionPerformed(evt);
            }
        });
        jPanel3.add(txtexpire, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 120, 30));

        Price1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Price1.setText("Status:");
        jPanel3.add(Price1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        txtstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstatusActionPerformed(evt);
            }
        });
        jPanel3.add(txtstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 120, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, 90));

        add.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel3.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 110, 33));

        update.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        update.setText("UPDATE");
        jPanel3.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 110, 33));

        delete.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel3.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 110, 33));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 630, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseClicked
        resetMenuColors();
        dashboard.setBackground(activeColor);
    }//GEN-LAST:event_dashboardMouseClicked

    private void dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardActionPerformed
        new dashboard(this.adminId).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dashboardActionPerformed

    private void productsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productsMouseClicked
        resetMenuColors();
        products.setBackground(activeColor);
    }//GEN-LAST:event_productsMouseClicked

    private void productsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productsActionPerformed

    private void reportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsMouseClicked
        new Reports(this.adminId).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_reportsMouseClicked

    private void reportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reportsActionPerformed

    private void userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseClicked
        new user(this.adminId).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_userMouseClicked

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        new user(this.adminId).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_userActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        int choice = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to log out?",
            "Logout Confirmation",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (choice == JOptionPane.YES_OPTION) {
            Session.clearSession();
            login lg = new login();
            lg.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void adminprofileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminprofileMouseClicked
        new adminprofile(this.adminId).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_adminprofileMouseClicked

    private void adminprofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminprofileActionPerformed
        new adminprofile(this.adminId).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_adminprofileActionPerformed

    private void txtID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtID1ActionPerformed

    private void txtproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtproductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtproductActionPerformed

    private void txtpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpriceActionPerformed

    private void txtquantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtquantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtquantityActionPerformed

    private void txtexpireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtexpireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtexpireActionPerformed

    private void txtstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstatusActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        String name = txtproduct.getText().trim();
        String priceStr = txtprice.getText().trim();
        String qtyStr = txtquantity.getText().trim();
        String expire = txtexpire.getText().trim();
        String status = txtstatus.getText().trim();
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Product name is required.");
            return;
        }
        double price = 0;
        int qty = 0;
        try {
            if (!priceStr.isEmpty()) price = Double.parseDouble(priceStr);
            if (!qtyStr.isEmpty()) qty = Integer.parseInt(qtyStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Price and quantity must be numbers.");
            return;
        }
        try (Connection conn = config.connectDB()) {
            if (conn == null) {
                JOptionPane.showMessageDialog(this, "Database connection failed.");
                return;
            }
            try (PreparedStatement pst = conn.prepareStatement(
                    "INSERT INTO tbl_products(product_name, price, quantity, expiration_date, status) VALUES (?,?,?,?,?)")) {
                pst.setString(1, name);
                pst.setDouble(2, price);
                pst.setInt(3, qty);
                pst.setString(4, expire.isEmpty() ? null : expire);
                pst.setString(5, status.isEmpty() ? null : status);
                pst.executeUpdate();
            }
            JOptionPane.showMessageDialog(this, "Product added successfully.");
            clearForm();
            displayProducts();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error adding product: " + e.getMessage());
        }
    }//GEN-LAST:event_addActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {
        String idStr = txtID1.getText().trim();
        if (idStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Select a product to update or enter ID.");
            return;
        }
        int pId;
        try {
            pId = Integer.parseInt(idStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid product ID.");
            return;
        }
        String name = txtproduct.getText().trim();
        String priceStr = txtprice.getText().trim();
        String qtyStr = txtquantity.getText().trim();
        String expire = txtexpire.getText().trim();
        String status = txtstatus.getText().trim();
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Product name is required.");
            return;
        }
        double price = 0;
        int qty = 0;
        try {
            if (!priceStr.isEmpty()) price = Double.parseDouble(priceStr);
            if (!qtyStr.isEmpty()) qty = Integer.parseInt(qtyStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Price and quantity must be numbers.");
            return;
        }
        try (Connection conn = config.connectDB()) {
            if (conn == null) {
                JOptionPane.showMessageDialog(this, "Database connection failed.");
                return;
            }
            try (PreparedStatement pst = conn.prepareStatement(
                    "UPDATE tbl_products SET product_name=?, price=?, quantity=?, expiration_date=?, status=? WHERE p_id=?")) {
                pst.setString(1, name);
                pst.setDouble(2, price);
                pst.setInt(3, qty);
                pst.setString(4, expire.isEmpty() ? null : expire);
                pst.setString(5, status.isEmpty() ? null : status);
                pst.setInt(6, pId);
                int updated = pst.executeUpdate();
                if (updated > 0) {
                    JOptionPane.showMessageDialog(this, "Product updated successfully.");
                    displayProducts();
                } else {
                    JOptionPane.showMessageDialog(this, "No product found with that ID.");
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error updating product: " + e.getMessage());
        }
    }

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        String idStr = txtID1.getText().trim();
        if (idStr.isEmpty()) {
            int row = jTable1.getSelectedRow();
            if (row >= 0) {
                Object o = jTable1.getValueAt(row, 0);
                idStr = o != null ? o.toString() : "";
            }
        }
        if (idStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Select a product to delete.");
            return;
        }
        int pId;
        try {
            pId = Integer.parseInt(idStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid product ID.");
            return;
        }
        int choice = JOptionPane.showConfirmDialog(this, "Delete this product?", "Confirm Delete", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (choice != JOptionPane.YES_OPTION) return;
        try (Connection conn = config.connectDB();
             PreparedStatement pst = conn != null ? conn.prepareStatement("DELETE FROM tbl_products WHERE p_id=?") : null) {
            if (pst == null) {
                JOptionPane.showMessageDialog(this, "Database connection failed.");
                return;
            }
            pst.setInt(1, pId);
            int deleted = pst.executeUpdate();
            if (deleted > 0) {
                JOptionPane.showMessageDialog(this, "Product deleted.");
                clearForm();
                displayProducts();
            } else {
                JOptionPane.showMessageDialog(this, "Product not found.");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error deleting product: " + e.getMessage());
        }
    }//GEN-LAST:event_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prodcutsadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prodcutsadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prodcutsadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prodcutsadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                if (!Session.isLoggedIn() || !Session.isAdmin()) {
                    JOptionPane.showMessageDialog(null, "You must log in first to access the system.", "Login Required", JOptionPane.WARNING_MESSAGE);
                    new login().setVisible(true);
                    return;
                }
                new prodcutsadmin(Session.getUserId()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Expiration;
    private javax.swing.JLabel Id;
    private javax.swing.JLabel Price;
    private javax.swing.JLabel Price1;
    private javax.swing.JLabel Product;
    private javax.swing.JLabel Quantity;
    private javax.swing.JButton add;
    private javax.swing.JButton adminprofile;
    private javax.swing.JButton dashboard;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton logout;
    private javax.swing.JButton products;
    private javax.swing.JButton reports;
    private javax.swing.JTextField txtID1;
    private javax.swing.JTextField txtexpire;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtproduct;
    private javax.swing.JTextField txtquantity;
    private javax.swing.JTextField txtstatus;
    private javax.swing.JButton update;
    private javax.swing.JButton user;
    // End of variables declaration//GEN-END:variables
}
